name: Build & Release macOS App
on:
  workflow_dispatch:
    tags:
          - "*"
  push:
    tags:
      - "*"
env:
  CI: true
jobs:
  build:
    runs-on: macos-14
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Get the version
        id: tag_version
        run: echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Install dependencies
        shell: bash
        run: |
          brew install graphicsmagick imagemagick swiftlint
          gem install fastlane
          bundle install
          pip install setuptools
          npm install --global create-dmg

      - name: Fastlane Release
        shell: bash
        run: fastlane release
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120 # x86 is slooooooow

      - name: Exract API_KEY
        shell: bash
        run: 'echo "$API_KEY" > apikey.json'
        env:
          API_KEY: ${{secrets.APPLE_API_KEY_JSON}}

      - name: Create DMG
        shell: bash
        run: |
          create-dmg ./output/PlayCover.app ./output
          mv ./output/*.dmg ./output/PlayCover_${{ env.TAG_NAME }}.dmg

      - name: Notarize DMG
        continue-on-error: true
        shell: bash
        run: |
          fastlane notarize_dmg package:output/PlayCover_${{ env.TAG_NAME }}.dmg

      - name: Clean Up
        shell: bash
        run: rm apikey.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: PlayCover_${{ env.TAG_NAME }}.dmg
          path: output/PlayCover_${{ env.TAG_NAME }}.dmg

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            output/PlayCover_${{ env.TAG_NAME }}.dmg
